PUZZLE = {
  # 11 => Color::DARK_BLUE,
  # 12 => Color::DARK_BLUE,
  13 => Color::LIGHT_GREEN,
  14 => Color::ORANGE,
  # 15 => Color::ORANGE,
  # 16 => Color::PURPLE,
  # 17 => Color::YELLOW,
  # 18 => Color::YELLOW,
  # 19 => Color::YELLOW,

  # 21 => Color::YELLOW,
  22 => Color::RED,
  # 23 => Color::YELLOW,
  # 24 => Color::YELLOW,
  25 => Color::PURPLE,
  26 => Color::LIGHT_BLUE,
  # 27 => Color::YELLOW,
  # 28 => Color::YELLOW,
  # 29 => Color::RED,

  # 31 => Color::LIGHT_BLUE,
  # 32 => Color::DARK_GREEN,
  # 33 => Color::ORANGE,
  # 34 => Color::YELLOW,
  # 35 => Color::LIGHT_GREEN,
  # 36 => Color::LIGHT_GREEN,
  37 => Color::LIGHT_BLUE,
  38 => Color::ORANGE,
  # 39 => Color::LIGHT_GREEN,

  # 41 => Color::PURPLE,
  # 42 => Color::ORANGE,
  # 43 => Color::YELLOW,
  # 44 => Color::DARK_BLUE,
  # 45 => Color::PINK,
  46 => Color::PINK,
  47 => Color::LIGHT_GREEN,
  # 48 => Color::LIGHT_GREEN,
  49 => Color::YELLOW,

  # 51 => Color::RED,
  52 => Color::ORANGE,
  # 53 => Color::PINK,
  # 54 => Color::LIGHT_BLUE,
  # 55 => Color::LIGHT_BLUE,
  # 56 => Color::LIGHT_BLUE,
  # 57 => Color::PURPLE,
  58 => Color::PURPLE,
  # 59 => Color::YELLOW,

  61 => Color::LIGHT_BLUE,
  # 62 => Color::RED,
  63 => Color::DARK_GREEN,
  64 => Color::DARK_BLUE,
  # 65 => Color::LIGHT_BLUE,
  # 66 => Color::LIGHT_BLUE,
  # 67 => Color::PURPLE,
  # 68 => Color::DARK_BLUE,
  # 69 => Color::YELLOW,

  # 71 => Color::DARK_GREEN,
  72 => Color::LIGHT_GREEN,
  73 => Color::ORANGE,
  # 74 => Color::LIGHT_GREEN,
  # 75 => Color::LIGHT_GREEN,
  # 76 => Color::LIGHT_GREEN,
  # 77 => Color::ORANGE,
  # 78 => Color::PINK,
  # 79 => Color::PURPLE,

  # 81 => Color::DARK_BLUE,
  # 82 => Color::DARK_BLUE,
  # 83 => Color::DARK_BLUE,
  84 => Color::PINK,
  85 => Color::LIGHT_BLUE,
  # 86 => Color::RED,
  # 87 => Color::RED,
  88 => Color::RED,
  # 89 => Color::RED,

  # 91 => Color::LIGHT_BLUE,
  # 92 => Color::LIGHT_BLUE,
  # 93 => Color::LIGHT_BLUE,
  # 94 => Color::RED,
  # 95 => Color::YELLOW,
  96 => Color::DARK_BLUE,
  97 => Color::DARK_GREEN
  # 98 => Color::DARK_GREEN,
  # 99 => Color::DARK_GREEN
}
