# row/col => color

PUZZLE_42 = {
  11 => Color::PURPLE,
  12 => Color::LIGHT_GREEN,
  13 => Color::YELLOW,
  14 => Color::DARK_GREEN,
  15 => Color::RED,
  16 => Color::ORANGE,
  17 => Color::LIGHT_BLUE,
  18 => Color::PINK,
  19 => Color::DARK_BLUE,

  # 21 => Color::YELLOW,
  # 22 => Color::RED,
  # 23 => Color::YELLOW,
  24 => Color::LIGHT_BLUE,
  25 => Color::PURPLE,
  26 => Color::YELLOW,
  27 => Color::LIGHT_GREEN,
  28 => Color::RED,
  29 => Color::DARK_GREEN,

  31 => Color::DARK_GREEN,
  32 => Color::LIGHT_BLUE,
  33 => Color::RED,
  34 => Color::LIGHT_GREEN,
  35 => Color::PINK,
  36 => Color::DARK_BLUE,
  37 => Color::YELLOW,
  38 => Color::ORANGE,
  39 => Color::PURPLE,

  # 41 => Color::PURPLE,
  # 42 => Color::ORANGE,
  43 => Color::LIGHT_GREEN,
  44 => Color::ORANGE,
  45 => Color::LIGHT_BLUE,
  46 => Color::DARK_GREEN,
  # 47 => Color::LIGHT_GREEN,
  # 48 => Color::LIGHT_GREEN,
  # 49 => Color::YELLOW,

  # 51 => Color::RED,
  # 52 => Color::ORANGE,
  # 53 => Color::PINK,
  54 => Color::RED,
  55 => Color::YELLOW,
  56 => Color::PINK,
  # 57 => Color::PURPLE,
  # 58 => Color::PURPLE,
  # 59 => Color::YELLOW,

  # 61 => Color::LIGHT_BLUE,
  # 62 => Color::RED,
  # 63 => Color::DARK_GREEN,
  64 => Color::DARK_BLUE,
  65 => Color::LIGHT_GREEN,
  66 => Color::PURPLE,
  67 => Color::ORANGE,
  # 68 => Color::DARK_BLUE,
  # 69 => Color::YELLOW,

  71 => Color::LIGHT_GREEN,
  72 => Color::PINK,
  73 => Color::LIGHT_BLUE,
  74 => Color::YELLOW,
  75 => Color::DARK_GREEN,
  76 => Color::RED,
  77 => Color::PURPLE,
  78 => Color::DARK_BLUE,
  79 => Color::ORANGE,

  81 => Color::DARK_BLUE,
  82 => Color::YELLOW,
  83 => Color::PURPLE,
  84 => Color::PINK,
  85 => Color::ORANGE,
  86 => Color::LIGHT_BLUE,
  # 87 => Color::RED,
  # 88 => Color::RED,
  # 89 => Color::RED,

  91 => Color::RED,
  92 => Color::DARK_GREEN,
  93 => Color::ORANGE,
  94 => Color::PURPLE,
  95 => Color::DARK_BLUE,
  96 => Color::LIGHT_GREEN,
  97 => Color::PINK,
  98 => Color::YELLOW,
  99 => Color::LIGHT_BLUE
}
